// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: enum.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
/// <summary>Holder for reflection information generated from enum.proto</summary>
public static partial class EnumReflection {

  #region Descriptor
  /// <summary>File descriptor for enum.proto</summary>
  public static pbr::FileDescriptor Descriptor {
    get { return descriptor; }
  }
  private static pbr::FileDescriptor descriptor;

  static EnumReflection() {
    byte[] descriptorData = global::System.Convert.FromBase64String(
        string.Concat(
          "CgplbnVtLnByb3RvKksKBmVHdWlsZBIPCgtFR1VJTERfTk9ORRAAEg4KCkVH",
          "VUlMRF9PTkUQARIOCgpFR1VJTERfVFdPEAISEAoMRUdVSUxEX1RIUkVFEANi",
          "BnByb3RvMw=="));
    descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
        new pbr::FileDescriptor[] { },
        new pbr::GeneratedClrTypeInfo(new[] {typeof(global::eGuild), }, null, null));
  }
  #endregion

}
#region Enums
public enum eGuild {
  [pbr::OriginalName("EGUILD_NONE")] None = 0,
  [pbr::OriginalName("EGUILD_ONE")] One = 1,
  [pbr::OriginalName("EGUILD_TWO")] Two = 2,
  [pbr::OriginalName("EGUILD_THREE")] Three = 3,
}

#endregion


#endregion Designer generated code
